In [5]:
from serial.tools.list_ports import comports

def arduino_port():
    for port in comports():
        if 'Arduino' in port.description:
            return port.name
    return None

port = arduino_port()
display(f'arduino contected: {port}')

'arduino contected: None'

In [2]:
from os import scandir
import numpy as np
import pandas as pd

def get_data(dataset_name, channels):    
    path = f'./data/{dataset_name}'
    
    with scandir(path) as it:
        entries = []
        for entry in it:
            if not entry.name.startswith('.') and entry.name.endswith('.csv') and entry.is_file():
                entries.append(entry)
    
    records = [None] * len(entries)
    targets = [None] * len(entries)
    
    for entry in entries:
        i = int(entry.name[:entry.name.index('_')])
        targets[i] = entry.name[entry.name.index('_')+1:entry.name.index('.')]
        records[i] = pd.read_csv(entry.path, usecols=channels)
    display('Data acquired from ' + dataset_name)
    return records, targets

records, targets = get_data('kaggle_dataset', ['emg0','emg1'])
display(targets)
display(len(records))
records[0]

'Data acquired from kaggle_dataset'

['neutral', 'flexion', 'extension', 'fist']

4

emg0  emg1
0        19    26
1        20    26
2        20    23
3        19    24
4        18    24
...     ...   ...
83605    23   111
83606    21    95
83607    23   109
83608    22   109
83609    21   109

[83610 rows x 2 columns]

In [3]:
from tqdm.auto import tqdm
from time import sleep, time

def seconds(): 
    return int(time())
    
def keep_runing(func, duration):
    results = []
    
    with tqdm(total=duration) as bar:
        
        current = seconds()
        end = current + duration
        
        while current < end:
            
            results.append(func())

            last = current
            current = seconds()
            bar.update(current - last)
    
    return np.array(results)

keep_runing(seconds, 1)

  0%|          | 0/1 [00:00<?, ?it/s]

array([1707991218, 1707991218, 1707991218, ..., 1707991218, 1707991218,
       1707991219])

In [6]:
from serial import Serial

def read_serial(serial, count):
    while True:
        try:
            values = serial.readline().decode('utf-8').strip().split()
        except UnicodeDecodeError:
            continue
        if len(values) == count:
            return [int(value) for value in values]
def capture(serial, count, target, duration, wait):
    
    display(f'Capturing for {target} will start in {wait} seconds')
    sleep(wait)
    record = keep_runing(lambda: read_serial(serial,count), duration)
    display(f'Captured {len(record)} data')

    return record

if port:
    with Serial(port, 9600, timeout=5) as serial:
        display(read_serial(serial,2))
        display(capture(serial, 2, 'flexion', 1, 1))

[422, 399]

'Capturing for flexion will start in 1 seconds'

  0%|          | 0/1 [00:00<?, ?it/s]

'Captured 168 data'

array([[328, 334],
       [352, 346],
       [333, 334],
       [319, 319],
       [373, 370],
       [304, 310],
       [419, 405],
       [289, 301],
       [429, 413],
       [280, 293],
       [425, 407],
       [271, 286],
       [409, 389],
       [265, 278],
       [357, 342],
       [262, 270],
       [295, 287],
       [266, 269],
       [258, 258],
       [304, 301],
       [245, 250],
       [354, 342],
       [231, 243],
       [370, 354],
       [224, 237],
       [370, 352],
       [217, 232],
       [362, 342],
       [214, 226],
       [314, 298],
       [212, 220],
       [255, 245],
       [215, 218],
       [216, 213],
       [249, 248],
       [201, 205],
       [302, 292],
       [189, 199],
       [326, 310],
       [183, 196],
       [330, 312],
       [179, 193],
       [327, 308],
       [177, 190],
       [287, 268],
       [177, 186],
       [229, 218],
       [179, 183],
       [188, 184],
       [210, 209],
       [171, 175],
       [264, 256],
       [162,

In [7]:
from serial import Serial

def capture_data(channels, targets, duration, wait, baud_rate):
    with Serial(arduino_port(), baud_rate, timeout=5) as serial:
        
        # discard first line to be sure new line is properly formatted
        serial.readline()
        serial.reset_input_buffer()

        records = []
        for target in targets:
            record = capture(serial, len(channels), target, duration, wait)
            df = pd.DataFrame(record, columns=channels)
            records.append(df)
    return records

if port:
    records = capture_data(['emg0','emg1'], ['neutral','flexion','extension'], 0.5, 0.5, 9600)
    display(len(records))
    display(records[0])

'Capturing for neutral will start in 0.5 seconds'

  0%|          | 0/0.5 [00:00<?, ?it/s]

'Captured 128 data'

'Capturing for flexion will start in 0.5 seconds'

  0%|          | 0/0.5 [00:00<?, ?it/s]

'Captured 94 data'

'Capturing for extension will start in 0.5 seconds'

  0%|          | 0/0.5 [00:00<?, ?it/s]

'Captured 96 data'

3

emg0  emg1
0     335   335
1     339   335
2     358   358
3     316   320
4     407   399
..    ...   ...
123   153   148
124   158   159
125   134   136
126   215   208
127   128   136

[128 rows x 2 columns]

In [8]:
from pathlib import Path
from IPython.display import FileLinks

def save_data(records, targets, name=None):
    
    if name is None:
        name = seconds()

    path = Path(f'./data/{name}')
    path.mkdir(exist_ok=True,)

    for i,target in enumerate(targets):
        target_path = path.joinpath(f'{i}_{target}.csv')
        records[i].to_csv(target_path, index=False)
    display(f'Data saved to {path}')

save_data(records, ['neutral','flexion','extension'], 'test')
FileLinks('./data/test/', recursive=False)

'Data saved to data\\test'

./data/test/
  0_neutral.csv
  0_relax.csv
  1_flex.csv
  1_flexion.csv
  2_extension.csv
  2_fist.csv

In [16]:
# number of sensor inputs
channel_count = 1
channels = [f'emg{i}' for i in range(channel_count)]
# when arduino is connected
targets = ['open','close']
save_as = 'test'
# when arduino is not connected
dataset = 'kaggle_dataset'

# recording time
duration = 30
wait = 5
baud_rate = 9600

if arduino_port() is None:
    records, targets = get_data(dataset, channels)
else:
    records = capture_data(channels, targets, duration, wait, baud_rate)
    save_data(records, targets, save_as)

'Data acquired from kaggle_dataset'

In [7]:
targets

['neutral', 'flexion', 'extension', 'fist']

In [54]:
len(records)

4

In [8]:
records

[       emg0  emg1
 0        19    26
 1        20    26
 2        20    23
 3        19    24
 4        18    24
 ...     ...   ...
 83605    23   111
 83606    21    95
 83607    23   109
 83608    22   109
 83609    21   109
 
 [83610 rows x 2 columns],
        emg0  emg1
 0       123   205
 1       127   252
 2       138   261
 3       141   244
 4       171   296
 ...     ...   ...
 28075    27   220
 28076    27   190
 28077    28   183
 28078    29   184
 28079    27   173
 
 [28080 rows x 2 columns],
        emg0  emg1
 0        19    26
 1        17    23
 2        16    21
 3        18    21
 4        17    20
 ...     ...   ...
 28075    23    80
 28076    22    73
 28077    20    73
 28078    22    81
 28079    24    72
 
 [28080 rows x 2 columns],
        emg0  emg1
 0        18    21
 1        17    21
 2        19    24
 3        19    25
 4        17    28
 ...     ...   ...
 28075    29    68
 28076    37    71
 28077    39    80
 28078    40    79
 28079    45    67
 

In [12]:
!git clone https://github.com/SebastianRestrepoA/EMG-pattern-recognition.git emg_pattern_recognition

fatal: destination path 'emg_pattern_recognition' already exists and is not an empty directory.


In [13]:
from emg_pattern_recognition.feature_extraction import features_estimation

In [9]:
record = records[0]
record

emg0  emg1
0        19    26
1        20    26
2        20    23
3        19    24
4        18    24
...     ...   ...
83605    23   111
83606    21    95
83607    23   109
83608    22   109
83609    21   109

[83610 rows x 2 columns]

In [15]:
list(record.items())

[('emg0',
  0       467
  1       321
  2       404
  3       316
  4       341
         ... 
  3247    122
  3248    266
  3249    123
  3250    262
  3251    127
  Name: emg0, Length: 3252, dtype: int32),
 ('emg1',
  0       438
  1       332
  2       389
  3       322
  4       335
         ... 
  3247    136
  3248    249
  3249    137
  3250    241
  3251    138
  Name: emg1, Length: 3252, dtype: int32)]

In [19]:
features_dfs = [
    features_estimation(np.array(channel), channel_name, 10, 25, 10)[0]
    for channel_name,channel in record.items()
]
features_dfs[0]

C:\Users\LeNoVo\Desktop\31Project\prosthetic-hand-control\src\data_classifier\emg_pattern_recognition\feature_extraction.py:169: RuntimeWarning: invalid value encountered in scalar divide
  return ULC / UHC
C:\Users\LeNoVo\miniforge3\envs\myjlabenv\Lib\site-packages\pywt\_multilevel.py:43: UserWarning: Level value of 4 is too high: all coefficients will experience boundary effects.
  warnings.warn(


EMG features were from channel emg0 extracted successfully
EMG features were from channel emg1 extracted successfully


0            1            2            3            4     \
VAR       1.280000     1.360000     2.080000     2.806400     3.830400   
RMS      18.434750    18.636523    19.453534    19.631607    19.737274   
IEMG    460.000000   465.000000   485.000000   489.000000   491.000000   
MAV      18.400000    18.600000    19.400000    19.560000    19.640000   
LOG       3.539551     3.556061     3.620515     3.631927     3.636027   
WL       19.000000    27.000000    34.000000    31.000000    30.000000   
ACC       0.760000     1.080000     1.360000     1.240000     1.200000   
DASDV     0.978945     1.307032     1.581139     1.541104     1.607275   
ZC        0.000000     0.000000     0.000000     0.000000     0.000000   
WAMP      0.000000     0.000000     0.000000     0.000000     0.000000   
MYOP      0.000000     0.000000     0.000000     0.000000     0.000000   
FR             NaN          NaN          NaN          NaN          NaN   
MNP     502.742502   513.798847   559.122832   569.316956   574.852765   
TP     7541.137537  7706.982705  8386.842479  8539.754347  8622.791480   
MNF       0.067170     0.060970     0.065420     0.064343     0.073281   
MDF       0.000000     0.000000     0.000000     0.000000     0.000000   
PKF       0.000000     0.000000     0.000000     0.000000     0.000000   
WENT      0.019449     0.020296     0.021885     0.034741     0.034712   

              5            6            7            8            9     ...  \
VAR       3.353600     2.265600     1.040000     4.422400     4.905600  ...   
RMS      19.008419    19.179155    19.227064    20.348956    20.241541  ...   
IEMG    473.000000   478.000000   480.000000   506.000000   503.000000  ...   
MAV      18.920000    19.120000    19.200000    20.240000    20.120000  ...   
LOG       3.578087     3.596988     3.606335     3.684106     3.673488  ...   
WL       31.000000    23.000000    17.000000    19.000000    20.000000  ...   
ACC       1.240000     0.920000     0.680000     0.760000     0.800000  ...   
DASDV     1.670828     1.338532     1.020621     1.274755     1.290994  ...   
ZC        0.000000     0.000000     0.000000     0.000000     0.000000  ...   
WAMP      0.000000     0.000000     0.000000     0.000000     0.000000  ...   
MYOP      0.000000     0.000000     0.000000     0.000000     0.000000  ...   
FR             NaN          NaN          NaN          NaN          NaN  ...   
MNP     533.277042   543.819543   547.294525   610.743792   604.265623  ...   
TP     7999.155629  8157.293147  8209.417882  9161.156880  9063.984351  ...   
MNF       0.068076     0.066687     0.057921     0.069296     0.058075  ...   
MDF       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
PKF       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
WENT      0.033119     0.027776     0.014803     0.034099     0.056491  ...   

               8349          8350          8351          8352          8353  \
VAR        8.425600      5.337600      3.849600      4.960000      7.241600   
RMS       26.042273     26.421204     25.595312     24.501429     24.428672   
IEMG     647.000000    658.000000    638.000000    610.000000    607.000000   
MAV       25.880000     26.320000     25.520000     24.400000     24.280000   
LOG        4.096232      4.131052      4.077838      3.997331      3.985710   
WL        40.000000     42.000000     38.000000     35.000000     38.000000   
ACC        1.600000      1.680000      1.520000      1.400000      1.520000   
DASDV      2.061553      2.198484      2.020726      2.031010      2.380476   
ZC         0.000000      0.000000      0.000000      0.000000      0.000000   
WAMP       0.000000      0.000000      0.000000      0.000000      0.000000   
MYOP       0.000000      0.000000      0.000000      0.000000      0.000000   
FR              NaN           NaN           NaN           NaN           NaN   
MNP      999.778080   1031.659122    968.328992    885.540360    879.160704   

In [17]:
features_dfs_renamed = [
    features_df.T.add_prefix(channel+'_')
    for features_df,channel in zip(features_dfs,channels)
]
features_dfs_renamed[0]

emg0_VAR    emg0_RMS  emg0_IEMG  emg0_MAV   emg0_LOG  emg0_WL  emg0_ACC  \
0    3978.5600  330.671620     8115.0    324.60  12.224179   2090.0     83.60   
1    4307.8400  298.114877     7270.0    290.80  11.622122   2591.0    103.64   
2    3712.4384  264.084986     6424.0    256.96  11.000421   2398.0     95.92   
3    3346.0736  240.150703     5827.0    233.08  10.536694   2095.0     83.80   
4    3836.8704  227.937886     5484.0    219.36  10.221887   2621.0    104.84   
..         ...         ...        ...       ...        ...      ...       ...   
318  3317.7696  184.729640     4388.0    175.52   9.227531   2405.0     96.20   
319  2753.4400  181.740034     4350.0    174.00   9.225503   1987.0     79.48   
320  3353.3696  185.737880     4412.0    176.48   9.248681   2433.0     97.32   
321  3244.1344  184.187839     4379.0    175.16   9.224160   2360.0     94.40   
322  2715.2736  181.711640     4352.0    174.08   9.230151   1980.0     79.20   

     emg0_DASDV  emg0_ZC  emg0_WAMP  emg0_MYOP  emg0_FR       emg0_MNP  \
0     99.947903      0.0        0.0       0.28      NaN  157333.607850   
1    117.404039      0.0        0.0       0.24      NaN  126688.790212   
2    111.563510      0.0        0.0       0.12      NaN   98990.915293   
3    100.266520      0.0        0.0       0.04      NaN   81310.184274   
4    118.102533      0.0        0.0       0.00      NaN   72063.792800   
..          ...      ...        ...        ...      ...            ...   
318  110.422484      0.0        0.0       0.00      NaN   46388.460926   
319   95.540785      0.0        0.0       0.00      NaN   45481.684043   
320  111.290348      0.0        0.0       0.00      NaN   46851.529715   
321  108.825931      0.0        0.0       0.00      NaN   46239.284745   
322   94.723721      0.0        0.0       0.00      NaN   45514.437854   

          emg0_TP  emg0_MNF  emg0_MDF  emg0_PKF  emg0_WENT  
0    2.360004e+06  0.063822       0.0       0.0   0.103639  
1    1.900332e+06  0.067338       0.0       0.0   0.138075  
2    1.484864e+06  0.065246       0.0       0.0   0.214809  
3    1.219653e+06  0.063784       0.0       0.0   0.168800  
4    1.080957e+06  0.067877       0.0       0.0   0.215427  
..            ...       ...       ...       ...        ...  
318  6.958269e+05  0.068345       0.0       0.0   0.384310  
319  6.822253e+05  0.063975       0.0       0.0   0.283425  
320  7.027729e+05  0.067828       0.0       0.0   0.305643  
321  6.935893e+05  0.067708       0.0       0.0   0.384993  
322  6.827166e+05  0.063772       0.0       0.0   0.272698  

[323 rows x 18 columns]

In [18]:
features = pd.concat(features_dfs_renamed, axis=1)
features

emg0_VAR    emg0_RMS  emg0_IEMG  emg0_MAV   emg0_LOG  emg0_WL  emg0_ACC  \
0    3978.5600  330.671620     8115.0    324.60  12.224179   2090.0     83.60   
1    4307.8400  298.114877     7270.0    290.80  11.622122   2591.0    103.64   
2    3712.4384  264.084986     6424.0    256.96  11.000421   2398.0     95.92   
3    3346.0736  240.150703     5827.0    233.08  10.536694   2095.0     83.80   
4    3836.8704  227.937886     5484.0    219.36  10.221887   2621.0    104.84   
..         ...         ...        ...       ...        ...      ...       ...   
318  3317.7696  184.729640     4388.0    175.52   9.227531   2405.0     96.20   
319  2753.4400  181.740034     4350.0    174.00   9.225503   1987.0     79.48   
320  3353.3696  185.737880     4412.0    176.48   9.248681   2433.0     97.32   
321  3244.1344  184.187839     4379.0    175.16   9.224160   2360.0     94.40   
322  2715.2736  181.711640     4352.0    174.08   9.230151   1980.0     79.20   

     emg0_DASDV  emg0_ZC  emg0_WAMP  ...  emg1_ZC  emg1_WAMP  emg1_MYOP  \
0     99.947903      0.0        0.0  ...      0.0        0.0       0.52   
1    117.404039      0.0        0.0  ...      0.0        0.0       0.32   
2    111.563510      0.0        0.0  ...      0.0        0.0       0.16   
3    100.266520      0.0        0.0  ...      0.0        0.0       0.04   
4    118.102533      0.0        0.0  ...      0.0        0.0       0.00   
..          ...      ...        ...  ...      ...        ...        ...   
318  110.422484      0.0        0.0  ...      0.0        0.0       0.00   
319   95.540785      0.0        0.0  ...      0.0        0.0       0.00   
320  111.290348      0.0        0.0  ...      0.0        0.0       0.00   
321  108.825931      0.0        0.0  ...      0.0        0.0       0.00   
322   94.723721      0.0        0.0  ...      0.0        0.0       0.00   

     emg1_FR       emg1_MNP       emg1_TP  emg1_MNF  emg1_MDF  emg1_PKF  \
0        NaN  154665.089386  2.319976e+06  0.063678       0.0       0.0   
1        NaN  125130.516086  1.876958e+06  0.067209       0.0       0.0   
2        NaN   97905.398121  1.468581e+06  0.065007       0.0       0.0   
3        NaN   79594.232302  1.193913e+06  0.064045       0.0       0.0   
4        NaN   70816.899286  1.062253e+06  0.067652       0.0       0.0   
..       ...            ...           ...       ...       ...       ...   
318      NaN   45684.064177  6.852610e+05  0.067736       0.0       0.0   
319      NaN   44251.163250  6.637674e+05  0.063890       0.0       0.0   
320      NaN   45894.649340  6.884197e+05  0.067517       0.0       0.0   
321      NaN   45384.768419  6.807715e+05  0.067108       0.0       0.0   
322      NaN   44125.926572  6.618889e+05  0.063897       0.0       0.0   

     emg1_WENT  
0     0.077196  
1     0.101334  
2     0.159849  
3     0.129806  
4     0.158283  
..         ...  
318   0.281949  
319   0.221517  
320   0.229980  
321   0.286456  
322   0.214050  

[323 rows x 36 columns]

In [19]:
record_X = features.values
record_X

array([[3.97856000e+03, 3.30671620e+02, 8.11500000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 7.71963008e-02],
       [4.30784000e+03, 2.98114877e+02, 7.27000000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 1.01333652e-01],
       [3.71243840e+03, 2.64084986e+02, 6.42400000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 1.59848657e-01],
       ...,
       [3.35336960e+03, 1.85737880e+02, 4.41200000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 2.29979793e-01],
       [3.24413440e+03, 1.84187839e+02, 4.37900000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 2.86456191e-01],
       [2.71527360e+03, 1.81711640e+02, 4.35200000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 2.14049505e-01]])

In [20]:
record_X.shape

(323, 36)

In [21]:
record_Xs = []
record_Xs.extend(record_X)
record_Xs.extend(record_X)
record_Xs
display(len(record_Xs))
display(len(record_Xs[0]))

646

36

In [22]:
X = np.array(record_Xs)
X

array([[3.97856000e+03, 3.30671620e+02, 8.11500000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 7.71963008e-02],
       [4.30784000e+03, 2.98114877e+02, 7.27000000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 1.01333652e-01],
       [3.71243840e+03, 2.64084986e+02, 6.42400000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 1.59848657e-01],
       ...,
       [3.35336960e+03, 1.85737880e+02, 4.41200000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 2.29979793e-01],
       [3.24413440e+03, 1.84187839e+02, 4.37900000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 2.86456191e-01],
       [2.71527360e+03, 1.81711640e+02, 4.35200000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 2.14049505e-01]])

In [23]:
X.shape

(646, 36)

In [24]:
record_y = [0]*features.shape[0]
len(record_y)

323

In [25]:
record_ys = []
record_ys.extend(record_y)
record_ys.extend(record_y)
len(record_ys)

646

In [26]:
y = np.array(record_ys)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [27]:
y.shape

(646,)

In [17]:
from emg_pattern_recognition.feature_extraction import features_estimation

# sampling frequency 
freq = 10
# sliding window
frame = 25
step = 10

def transform(records):
    record_Xs, record_ys = [],[]
    for target_idx,record in enumerate(records):
        
        features_dfs = []
        
        for channel_name,channel in record.items():
            features_df = features_estimation(np.array(channel), channel_name, freq, frame, step)[0]
            features_df_renamed = features_df.T.add_prefix(channel_name+'_')
            features_dfs.append(features_df_renamed)
        
        features = pd.concat(features_dfs, axis=1)

        
        record_X = features.values
        record_y = [target_idx]*features.shape[0]

        record_Xs.extend(record_X)
        record_ys.extend(record_y)
    
    return np.array(record_Xs), np.array(record_ys)

X,y = transform(records)

C:\Users\LeNoVo\Desktop\31Project\prosthetic-hand-control\src\data_classifier\emg_pattern_recognition\feature_extraction.py:169: RuntimeWarning: invalid value encountered in scalar divide
  return ULC / UHC
C:\Users\LeNoVo\miniforge3\envs\myjlabenv\Lib\site-packages\pywt\_multilevel.py:43: UserWarning: Level value of 4 is too high: all coefficients will experience boundary effects.
  warnings.warn(


EMG features were from channel emg0 extracted successfully


C:\Users\LeNoVo\Desktop\31Project\prosthetic-hand-control\src\data_classifier\emg_pattern_recognition\feature_extraction.py:169: RuntimeWarning: invalid value encountered in scalar divide
  return ULC / UHC
C:\Users\LeNoVo\miniforge3\envs\myjlabenv\Lib\site-packages\pywt\_multilevel.py:43: UserWarning: Level value of 4 is too high: all coefficients will experience boundary effects.
  warnings.warn(


EMG features were from channel emg0 extracted successfully


C:\Users\LeNoVo\Desktop\31Project\prosthetic-hand-control\src\data_classifier\emg_pattern_recognition\feature_extraction.py:169: RuntimeWarning: invalid value encountered in scalar divide
  return ULC / UHC
C:\Users\LeNoVo\miniforge3\envs\myjlabenv\Lib\site-packages\pywt\_multilevel.py:43: UserWarning: Level value of 4 is too high: all coefficients will experience boundary effects.
  warnings.warn(


EMG features were from channel emg0 extracted successfully


C:\Users\LeNoVo\Desktop\31Project\prosthetic-hand-control\src\data_classifier\emg_pattern_recognition\feature_extraction.py:169: RuntimeWarning: invalid value encountered in scalar divide
  return ULC / UHC
C:\Users\LeNoVo\miniforge3\envs\myjlabenv\Lib\site-packages\pywt\_multilevel.py:43: UserWarning: Level value of 4 is too high: all coefficients will experience boundary effects.
  warnings.warn(


EMG features were from channel emg0 extracted successfully


In [35]:
X

array([[3.97856000e+03, 3.30671620e+02, 8.11500000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 7.71963008e-02],
       [4.30784000e+03, 2.98114877e+02, 7.27000000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 1.01333652e-01],
       [3.71243840e+03, 2.64084986e+02, 6.42400000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 1.59848657e-01],
       ...,
       [3.73363840e+03, 1.90050625e+02, 4.49900000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 2.25764108e-01],
       [3.28981440e+03, 1.83057805e+02, 4.34600000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 2.98782192e-01],
       [3.04495360e+03, 1.84524036e+02, 4.40200000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 2.09536497e-01]])

In [36]:
X.shape

(983, 36)

In [37]:
y.shape

(983,)

In [33]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [53]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, shuffle=True)

model = RandomForestClassifier(criterion='entropy')
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.6764004767580453

In [75]:
features_estimation(np.array([randint(0,1024)]*(frame+1)), 'live', freq, frame, step)[0]

EMG features were from channel live extracted successfully


C:\Users\LeNoVo\Desktop\31Project\prosthetic-hand-control\src\data_classifier\emg_pattern_recognition\feature_extraction.py:169: RuntimeWarning: invalid value encountered in scalar divide
  return ULC / UHC
C:\Users\LeNoVo\miniforge3\envs\myjlabenv\Lib\site-packages\pywt\_multilevel.py:43: UserWarning: Level value of 4 is too high: all coefficients will experience boundary effects.
  warnings.warn(


0
VAR    0.000000e+00
RMS    9.850000e+02
IEMG   2.462500e+04
MAV    9.850000e+02
LOG    1.995413e+01
WL     0.000000e+00
ACC    0.000000e+00
DASDV  0.000000e+00
ZC     0.000000e+00
WAMP   0.000000e+00
MYOP   1.000000e+00
FR              NaN
MNP    1.437948e+06
TP     2.156921e+07
MNF    6.181803e-02
MDF    0.000000e+00
PKF    0.000000e+00
WENT   1.986391e-31

In [57]:
from random import randint
import sys

try:
    while True:
        x = 

        print(x, end='\r')
        sleep(0.1)
        print(' '*10, end='\r')
except KeyboardInterrupt:
    pass

EMG features were from channel live extracted successfully
Empty DataFrame
Columns: []
EMG features were from channel live extracted successfully, MYOP, FR, MNP, TP, MNF, MDF, PKF, WENT]
Empty DataFrame
Columns: []
EMG features were from channel live extracted successfully, MYOP, FR, MNP, TP, MNF, MDF, PKF, WENT]
Empty DataFrame
Columns: []
EMG features were from channel live extracted successfully, MYOP, FR, MNP, TP, MNF, MDF, PKF, WENT]
Empty DataFrame
Columns: []
EMG features were from channel live extracted successfully, MYOP, FR, MNP, TP, MNF, MDF, PKF, WENT]
Empty DataFrame
Columns: []
EMG features were from channel live extracted successfully, MYOP, FR, MNP, TP, MNF, MDF, PKF, WENT]
Empty DataFrame
Columns: []
EMG features were from channel live extracted successfully, MYOP, FR, MNP, TP, MNF, MDF, PKF, WENT]
Empty DataFrame
Columns: []
EMG features were from channel live extracted successfully, MYOP, FR, MNP, TP, MNF, MDF, PKF, WENT]
Empty DataFrame
Columns: []
EMG features were